apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets-depl
  template:
    metadata:
      labels:
        app: tickets-depl
    spec:
      containers:
        - name: tickets-depl
          image: sayzera1/tickets
          env:
            - name: MONGO_URI
              value: "mongodb://auth-mongo-srv:27017/tickets"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  type: ClusterIP
  ports:
    - name: tickets-depl
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: tickets-depl
